_format_version: "2.1"

services:

  - name: echo-server
    url: http://192.168.1.11:6969
    routes:
      - name: echo
        paths:
          - /echo
  - host: host.docker.internal
    port: 9091
    name: sb-service
    path: /serve
    routes:
      - name: sb-service
        paths:
          - /sb
        strip_path: true
# plugins section
plugins:
  - name: correlation-id
    config:
      header_name: Request-ID
      generator: tracker
      echo_downstream: false
  - name: prometheus
    config:
      status_code_metrics: true
      latency_metrics: true
      bandwidth_metrics: true
      upstream_health_metrics: true


